---
- name: Install composer.phar
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin creates=/usr/bin/composer

- name: Rename composer.phar to composer
  command: mv /usr/bin/composer.phar /usr/bin/composer creates=/usr/bin/composer
