---
- name: Install epel yum repository
  yum: name="http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm"

- name: Install remi yum repository
  yum: name="http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"

- name: Install PHP 5.6
  yum: name={{ item }} state=present enablerepo=remi-php56
  with_items:
    - php
    - php-cli
    - php-common
    - php-pdo
    - php-fpm
    - php-mcrypt
    - php-mbstring
    - php-opcache
    - php-pecl-memcache
    - php-xml

- name: Start and Enable php-fpm
  service: name=php-fpm state=started enabled=yes
